heat_template_version: 2015-10-15

description: Simple template to deploy a single compute instance

parameters:
    image:
        type: string
        label: Image name or ID
        description: OSv image to be used for server
        default: d5089e5e-438c-490a-bc31-fd808449b54b
        constraints:
            - custom_constraint: glance.image
    flavor:
        type: string
        label: Flavor
        description: Flavor to be used for the server
        default: kvm.m1.small
        constraints:
            - custom_constraint: nova.flavor
    private_network: 
        type: string
        label: Private network name or ID
        description: Private network to attach server to.
        default: private-9e4e502e9d804ed88baca5bda63217ad
    public_network:
        type: string
        label: Public network name or ID
        description: Public network with floating IP addresses.
        default: public
    cluster_size:
        type: number
        label: Cluster size
        description: Number of OSv instances
        default: 1
    worker_processes:
        type: number
        label: Number of worker processes
        description: Number of worker processes
        default: 2

resources:
    security_group:
        type: OS::Neutron::SecurityGroup
        properties:
            name: mpirun
            rules:
                - remote_ip_prefix: 0.0.0.0/0
                  protocol: tcp
                  port_range_min: 0
                  port_range_max: 65535
                - protocol: icmp

    master_instance:
        type: MIKE::OSv::Instance
        properties:
            image: { get_param: image }
            flavor: { get_param: flavor }
            private_network: { get_param: private_network }
            security_group: { get_resource: security_group }
            user_data:
                str_replace:
                    params: 
                        $NP: { get_param: worker_processes }
                        $WORKERS: { list_join: [',', get_attr: [osv_cluster, ip]] }
                    template: |
                        run:
                            - POST: /env/WM_PROJECT_DIR
                              val: /openfoam
                            - PUT: /app
                              command: /tools/mount-nfs.so nfs://10.254.1.27/export/?uid=0 /data
                            - PUT: /app
                              command: /usr/bin/mpirun -np $NP -x WM_PROJECT_DIR=/openfoam -x MPI_BUFFER_SIZE=20000000 -H localhost,$WORKERS --allow-run-as-root /usr/bin/simpleFoam.so -case /data/mik3d_1h-$NP -parallel

    osv_cluster:
        type: OS::Heat::ResourceGroup
        properties:
            count: { get_param: cluster_size }
            resource_def:
                type: MIKE::OSv::Instance
                properties:
                    image: { get_param: image }
                    flavor: { get_param: flavor }
                    private_network: { get_param: private_network }
                    security_group: { get_resource: security_group }
                    user_data: |
                        run:
                            - POST: /env/WM_PROJECT_DIR
                              val: /openfoam
                            - PUT: /app
                              command: /tools/mount-nfs.so nfs://10.254.1.27/export/?uid=0 /data

    master_floating_ip:
        type: MIKE::OSv::FloatingIp
        properties:
            server_id: { get_attr: [master_instance, instance] }

outputs:
    master_name:
        description: Name of the master instance
        value: { get_attr: [master_instance, name] }
    master_ip:
        description: The IP of the master instance
        value: { get_attr: [master_floating_ip, ip] }
    slave_ips:
        description: Slave IPs
        value: { get_attr: [osv_cluster, ip] }
    command:
        description: mpirun command to execute
        value:
            str_replace:
                params: 
                    $NP: { get_param: worker_processes }
                    $WORKERS: { list_join: [',', get_attr: [osv_cluster, ip]] }
                template: |
                    /usr/bin/mpirun -np $NP -x WM_PROJECT_DIR=/openfoam -x MPI_BUFFER_SIZE=20000000 -H localhost,$WORKERS --allow-run-as-root /usr/bin/simpleFoam.so -case /data/mik3d_1h-$NP -parallel

